spring:
  datasource:
    url: jdbc:oracle:thin:@10.5.6.32:1521:NITC4
    username: pscnepalcommercialdatabaseu1
    password: root1
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
server:
  port: 8090